---
Name: fromholdio-featureimage
---
Page:
  extensions:
    - Fromholdio\FeatureImage\Extensions\FeatureImagePageExtension

SilverStripe\ORM\DatabaseAdmin:
  extensions:
    - Fromholdio\FeatureImage\Extensions\DatabaseAdminExtension

---
Name: fromholdio-featureimage-multisites
Only:
  moduleexists:
    - 'innoweb/silverstripe-social-metadata'
    - 'symbiote/silverstripe-multisites'
After: '#socialmeta'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Fromholdio\FeatureImage\Extensions\FeatureImageSiteExtension

---
Name: fromholdio-featureimage-configured-multisites
Only:
  moduleexists:
    - 'innoweb/silverstripe-social-metadata'
    - 'fromholdio/silverstripe-configured-multisites'
After: '#socialmeta'
---
Fromholdio\ConfiguredMultisites\Model\Site:
  extensions:
    - Fromholdio\FeatureImage\Extensions\FeatureImageSiteExtension

---
Name: fromholdio-featureimage-nomultisites
Except:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
    - 'fromholdio/silverstripe-configured-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Fromholdio\FeatureImage\Extensions\FeatureImageSiteConfigExtension
