---
Name: fromholdio-featureimage
---
Page:
  extensions:
    - Fromholdio\FeatureImage\Extensions\FeatureImagePageExtension

---
Name: fromholdio-featureimage-multisites
Only:
  moduleexists:
    - 'innoweb/silverstripe-social-metadata'
After: '#socialmeta'
---
Symbiote\Multisites\Model\Site:
  extensions:
    - Fromholdio\FeatureImage\Extensions\FeatureImageSiteExtension

---
Name: fromholdio-featureimage-nomultisites
Except:
  moduleexists:
    - 'symbiote/silverstripe-multisites'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Fromholdio\FeatureImage\Extensions\FeatureImageSiteConfigExtension